### ISSUE TITLE
team meeting minutes

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-admin#138]
Create a new GH issue every year and record the agenda / minutes for each meeting as a comment on that issue.

This makes minutes a little more discoverable and searchable.

**Comment by hjoliver** [comment]
Not a bad idea. Maybe this variation would be even better though:

- add a meeting Issue template to the cylc-admin repo
- just open a new "meeting" issue before each meeting, tweak the date, and populate the usual bits
- have an annual meeting milestone that can be closed every year, to hide older stuff

**Comment by oliver-sanders** [comment]
I think a new issue for each meeting is overkill and more maintenance.

Here's the 2021 meetings issue on the Jupyter Server "team compass" (their version of cylc-admin):

https://github.com/jupyter-server/ team-compass/issues/4

I quite like this approach.

**Comment by hjoliver** [comment]
From last project meeting, we're going with this approach. https://github.com/cylc/cylc-admin/issues/139
