### ISSUE TITLE
release: 8.0rc3

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-admin#153]
### Release Progress

Issue to track the coordinated release of multiple Cylc components.

**Required for all minor releases of cylc-flow.**

See [the release docs](https://github.com/cylc/cylc-admin/blob/master/docs/howto/create-a-release.md) for first time instructions and more info.

#### Prep:

* [x] The release lead should be assigned to this issue.
* [x] Ensure all milestones complete.
* [x] Test cylc-doc (run a test build, perform any required fixes).
* [x] Run cylc-flow functional tests against locally available platforms.
* [x] List the milestones for release below (delete entries as appropriate).

#### Complete and close milestones for release:

* [x] ~metomi-isodatetime:~
* [x] cylc-flow: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-flow/98)](
  https://github.com/cylc/cylc-flow/milestone/98)
* [x] cylc-ui: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-ui/13)](
  https://github.com/cylc/cylc-ui/milestone/13)
* [x] cylc-uiserver: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-uiserver/11)](
  https://github.com/cylc/cylc-uiserver/milestone/11)
* [x] metomi/rose: [![](
  https://img.shields.io/github/milestones/issues-open/metomi/rose/79)](
  https://github.com/metomi/rose/milestone/79)
* [x] cylc-rose: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-rose/10)](
  https://github.com/cylc/cylc-rose/milestone/10)
* [x] cylc-doc: [![](
  https://img.shields.io/github/milestones/issues-open/cylc/cylc-doc/6)](
  https://github.com/cylc/cylc-doc/milestone/6)

#### PyPi / GitHub releases:

> Ensure all Cylc components are pinned to the correct version of cylc-flow.

> Trigger releases via GitHub actions.

* [x] ~metomi-isodatetime~
* [x] cylc-flow (bump metomi-isodatetime if required)
* [x] cylc-ui
* [x] cylc-uiserver ([update the ui](https://github.com/cylc/cylc-uiserver/actions/workflows/update_ui.yml) version before releasing)
* [x] metomi-rose (bump metomi-isodatetime if required)
* [x] cylc-rose

#### Forge (check dependencies match):

> Pull requests will be automatically opened on the conda-forge feedstocks
> after the pypi releases.
>
> If not, create a new branch, change the version, reset the build number and
> update the hash from the PyPi website.
> Finally trigger a rerender in a comment.

> Ensure dependencies are up to date and follow instructions on the PR. Some
> repos may maintain a list of conda dependencies locally.

* [x] ~metomi-isodatetime~ (no new release needed)
* [x] cylc-flow
* [x] ~cylc-ui~ (not publishing separately?)
* [x] cylc-uiserver
* [x] metomi-rose
* [x] cylc-rose

> It make take a couple of hours for a release to become available.
> Use `conda search <package>` to determine when it's ready.

#### Misc (after the above has been completed):

* cylc-doc
  * [x] bump intersphinx versions if required (`cylc-doc/src/conf.py`)
  * [x] review [deployment instructions](https://github.com/cylc/cylc-doc#deploying)
  * [x] deploy (run the "deploy" workflow on GitHub Actions) (can be re-deployed later if necessary)
* metomi-rose
  * [x] build & deploy documentation - https://github.com/metomi/rose/pull/2595
* [x] discourse post

#### Metadata:

> Update project versions to the next milestone
> AND pin downstream components to the next cylc-flow dev release.

* [x] cylc-flow - https://github.com/cylc/cylc-flow/pull/4893
* [x] cylc-uiserver (pin to latest cylc-flow)  - https://github.com/cylc/cylc-uiserver/pull/358
* [x] cylc-rose (pin to latest cylc-flow) - https://github.com/cylc/cylc-rose/pull/143
* [x] metomi-rose - https://github.com/metomi/rose/pull/2596

#### Finally:

* [ ] close this issue :rocket:

**Comment by oliver-sanders** [comment]
When releasing cylc-flow, remember to `git grep nightly` and switch any cylc-doc URLs over to `latest`.

**Comment by hjoliver** [comment]
> When releasing cylc-flow, remember to `git grep nightly` and switch any cylc-doc URLs over to `latest`.

There are no matches in cylc-flow.  Should there be?

**Comment by oliver-sanders** [comment]
Ah sorry, it was an RC4 PR which has not yet been merged - https://github.com/cylc/cylc-flow/pull/4860

**Comment by oliver-sanders** [comment]
@hjoliver 

Sorry my bad, there's a missing instruction here:

> Trigger releases via GitHub actions.

The repos are listed in release order, however, the issue template doesn't tell you to do them in order.

No probs, don't need to go closing the PRs but they will fail until the relevant bits have been released due to version pinning.

> cylc-uiserver ([update the ui](https://github.com/cylc/cylc-uiserver/actions/workflows/update_ui.yml) version before releasing)

There is a GH action which updates the UI from the official build automatically, follow the link in the above line. Note the UI must be released before it can be updated in the UIS.

**Comment by oliver-sanders** [comment]
> Complete and close milestones for release:

No need to close the milestones, the release actions do this for you automatically.

**Comment by oliver-sanders** [comment]
Updated the instructions - https://github.com/cylc/cylc-admin/pull/154

**Comment by oliver-sanders** [comment]
Ticked off the "discourse post" item, good to close?
