### ISSUE TITLE
Tools for conda feedstock dependency updates?

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-admin#156]
The 8.0rc3 release has shown it is too easy to forget to update dependencies on the conda-forge feedstock repos. If we could help automate it, either looking for a pre-existing tool or creating some kind of GH Actions workflow that can cross-reference `setup.cfg` and the `recipe/meta.yaml` to make sure the dependencies match

**Comment by oliver-sanders** [comment]
> The 8.0rc3 release has shown it is too easy to forget to update dependencies on the conda-forge feedstock repos

There's a checkbox on the conda-forge PR which should only be ticked once the task is completed. The PR should not be merged until all checkboxes are completed.

> make sure the dependencies match

At release time I have the conda-forge recipe open and the `setup.cfg` open, then go through all of the dependencies in both one by one. We kinda have to do this to maintain the outputs anyway (can't be automated as the outputs are manually defined).

> if we could help automate it

Here's the closest tool I can find (https://pypi.org/project/poetry2conda/). It generates conda environment files from poetry setup files, however, cannot generate an entire recipe file, handle outputs or anything like that. To work properly an automation tool would need to support:
* Conda forge outputs (which don't match the setuptools optional dependencies).
* The different dependency formats between setuptools and conda.
* Differing dependency names between setuptools and conda.
* Non-setuptools dependencies (e.g. graphviz, these may require version matching to setuptools dependencies).
* Jinja2 templating of the recipe file.

So nice idea but I think automating the dep updates isn't realistic.

As an afterthought we could add `pip check` as a conda-forge test. It wouldn't tell us whether the setuptools and Conda deps match, however, it would tell you if they conflict preventing totally broken releases.

**Comment by hjoliver** [comment]
Fair enough. I think it will suffice to review our documentation (in the "release process" cylc-admin Issue template) each time, and make it more explicit the release manager(s) don't find it clear enough.

**Comment by hjoliver** [comment]
I'll close this @MetRonnie - reopen if you disagree and have more to add.
