### ISSUE TITLE
Use cylc globally as namespace for cylc, cylc-uiserver, cylc-xtriggers, etc

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-admin#25]
We have a few more projects now under the cylc organisation. So far I think they are all related to the Cylc core package/module - `cylc` is a package that contains the `cylc` module, but package and module are also used interchangeably.

Instead of having packages `cylc` with module `cylc`, `cylc-uiserver` with module `cylc_uiserver`, `cylc-xtriggers` with `cylc_xtriggers`, we can use [namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/). So we would have:

- `cylc/cylc` repository for `cylc` package, with the `cylc` module
- `cylc/cylc-uiserever` repository for `cylc-uiserver` package, with the `cylc.uiserver` namespace module
- `cylc/cylc-xtriggers` repository for `cylc-xtriggers` package, with `cylc.xtriggers` namespace module (collides with existing module from `cylc/cylc`)

And so on. This means that packages related to the Cylc core could share the namespace. So for a user, instead of writing:

```python
from cylc.config import SuiteConfig
from cylc_xtriggers import SudoXtriggerForExample
```

s/he could write:

```python
from cylc.config import SuiteConfig
from cylc.xtriggers import SudoXtriggerForExample
```

This assuming `cylc` and `cylc-xtriggers` have been installed.

I have not used this technique before, but it resembles something similar from Java (modules with common groupId), and the new scoped packages from NPM (e.g. `@babel/core`, `@vue/cli-service`).

This issue is both to check with others what is their opinion on this approach, and also to document in further comments my findings while experimenting with it, so that reasons for using or not are clear/transparent to others. Won't have much action until Cylc `setup.py` is merged first.

Feel free to add comments 👍

**Comment by hjoliver** [comment]
Note we decided in last meeting to rename `cylc` (scheduler) to `cylc-flow` (@sadielbartholomew's excellent suggestion 👍 )

**Comment by hjoliver** [comment]
Sounds good to me @kinow - if we can do this.

**Comment by hjoliver** [comment]
https://packaging.python.org/guides/packaging-namespace-packages/

**Comment by kinow** [comment]
>Note we decided in last meeting to rename cylc (scheduler) to cylc-flow (@sadielbartholomew's excellent suggestion 👍 )

Neat! So the repository in `cylc/cylc` will actually be a package in PYPI/Conda/etc called `cylc-flow`? But with the same modules (i.e. `cylc`, `cylc.version`, `cylc.config`, `cylc.scheduler`)?

**Comment by kinow** [comment]
From their docs:

>Namespace packages can be useful for a large collection of loosely-related packages (such as a large corpus of client libraries for multiple products from a single company). However, namespace packages come with several caveats and are not appropriate in all cases. A simple alternative is to use a prefix on all of your distributions such as import mynamespace_subpackage_a (you could even use import mynamespace_subpackage_a as subpackage_a to keep the import object short).

Also looks like we would be going with _native namespace packages_ after their note:

>Use native namespace packages. This type of namespace package is defined in PEP 420 and is available in Python 3.3 and later. This is recommended if packages in your namespace only ever need to support Python 3 and installation via pip.

So if you read that document, you can skip the other sections if you would like.

And they mention PEP420 too, which defined namespace packages: https://www.python.org/dev/peps/pep-0420/

**Comment by hjoliver** [comment]
> > Note we decided in last meeting to rename cylc (scheduler) to cylc-flow (@sadielbartholomew's excellent suggestion 👍 )
> 
> Neat! So the repository in `cylc/cylc` will actually be a package in PYPI/Conda/etc called `cylc-flow`? But with the same modules (i.e. `cylc`, `cylc.version`, `cylc.config`, `cylc.scheduler`)?

To be explicit, I imagine we will also rename the `cylc/cylc` repository to `cylc/cylc-flow`; and still use the `cylc` namespace for everything (`cylc.config` etc.) ... does that make sense.

**Comment by kinow** [comment]
Finished reading the PEP 420, but did not find anything that seemed likely to cause issues to us. I think the only way to confirm what could go wrong it trying it later.

**Comment by kinow** [comment]
Note to self: package using namespaces that we are also using: [protobuf](https://github.com/protocolbuffers/protobuf/blob/6b4b9869eca84d00fd9a1ca93d0e29ba20e8e699/python/setup.py#L270)

**Comment by hjoliver** [comment]
@kinow - can we close this now?

**Comment by kinow** [comment]
Yup!!! 🎉
