### ISSUE TITLE
Add GitHub topics

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-admin#3]
the `cylc/cylc` project is lacking GitHub topics. Some possible topics include `workflow`, `scheduling`, or `meta-scheduler`. I think `metascheduler` and `meta-scheduler` are both empty in GitHub right now :scream: 

This could result in other users finding Cylc when searching for these topics. This happens with frequency when people go to the repository of another tool with topics, and click on these topics to explore and find related software.

**Comment by hjoliver** [comment]
I've added a bunch of topics (which can be adjusted any time).
