### ISSUE TITLE
Release process checklist.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-admin#39]
We need to clearly define the release process for the release manager to follow (including online documentation update).

This will get more complicated at Cylc 8.

**Comment by kinow** [comment]
(throwing some content here, anybody feel free to edit/enhance it)

## PYPI projects

- Verify you have an account on PYPI or Test PYPI (both preferably, and bonus points if 2FA activated)

Steps:

1. Update versions in the Python project (location may vary depending on the project)
2. Update `setup.py`, especially dependencies
3. Update project badge - if any - in the `README.md` file

**Comment by wxtim** [comment]
in cylc-flow update cylc/flow/__init__ > version=???

**Comment by kinow** [comment]
I think we can close this as we already have some docs in cylc-admin (thanks @wxtim !) and also some more info in the cylc-flow repository. WDYT @hjoliver ?

**Comment by hjoliver** [comment]
(Closing - we now have an Issue template for this).
