### ISSUE TITLE
Create a new logo for Cylc

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-admin#5]
Do we need a new logo for Cylc? Is our logo OK, or is it too similar to logos of other projects? Maybe we can have an open call for submissions for logo ideas & designs.

**Comment by hjoliver** [comment]
Yes may be "too similar" to the Google Assistant logo!

![image](https://user-images.githubusercontent.com/2362137/49046810-44bc0d80-f23a-11e8-923c-76d4490db756.png)

![image](https://user-images.githubusercontent.com/2362137/49046839-61f0dc00-f23a-11e8-9438-d9e387e9e41d.png)

**Comment by kinow** [comment]
Indeed it is!

I'd be keen to try to come up with a few designs, but there's a whole community building design for OSS projects too here: https://www.reddit.com/r/fossdesign

**Comment by hjoliver** [comment]
The color shades (esp. green) are slightly different!

For the record, I created the current logo by abstracting/evolving a small "cylc gui" icon that represented a few tasks in a workflow graph.  I'm pretty sure it predates Google Assistant too. 

Happy to try for something new though ... but it had better be good!

**Comment by kinow** [comment]
Maybe we can simply modify the current logo a little bit? Keeping colours and/or shapes. Here's a quick example (finished packing for Melbourne, and didn't want to write code before sleeping today :grimacing: )

![cylc1 svg](https://user-images.githubusercontent.com/304786/49284481-9ba33a80-f4f9-11e8-98d7-8249ecc61e2c.png)

All fonts license OK, done in Inkscape :+1: 

[cylc1.svg.zip](https://github.com/cylc/cylc-admin/files/2632919/cylc1.svg.zip)

**Comment by hjoliver** [comment]
Nice! Actually I really like this one, although maybe with a different font: 

![log](https://user-images.githubusercontent.com/2362137/49319099-53af0280-f54f-11e8-96df-698311367d6e.png)

It has a kind of retro sci-fi cartoon vibe (Jetsons?).

**Comment by kinow** [comment]
I am re-watching Star Trek from the 60's. Might be my subconscious playing with my artistic mind!

**Comment by kinow** [comment]
![cylc2 svg](https://user-images.githubusercontent.com/304786/49323809-54af5680-f586-11e8-912c-c0fa8429639b.png)

[cylc2.svg.zip](https://github.com/cylc/cylc-admin/files/2635562/cylc2.svg.zip)

**Comment by matthewrmshin** [comment]
I don't normally like fancy fonts, but Aref Ruqaa is quite nice in this case - it goes well with the rounded logo.

**Comment by kinow** [comment]
I liked Aref, but not Alice :confused: Also liked Universalis, Ubuntu, and Lato. Oh, and if you look at the circles around it... they do resemble a rose... don't they? :grimacing:

**Comment by hjoliver** [comment]
None of the fonts above quite do it for me.  Although I am coming around to Aref Ruqaa (surprising as I don't normally like serif fonts).

How about the Google Font that I chose to go with the current logo?  
![image](https://user-images.githubusercontent.com/2362137/53519684-abeaa600-3b38-11e9-93e5-d53d537af2c1.png)

It's called Titillium Web: https://fonts.google.com/specimen/Titillium+Web

(Just in case)

**Comment by kinow** [comment]
Need to practice more Vue.js, so creating these projects help me experiment with a few things... the code is ugly, but I was playing with TypeScript and will try to add a Jest unit test later...

https://kinow.github.io/svg-logo-composer/

Just type the font, change the settings, position the text, and a screen shot + font name + dimensions should be enough to replicate later :grimacing: we just need to choose a font from Google Fonts.

Then if there's consensus, I can quickly put everything together in Inkscape :+1: 

Here's an example with Titillium Web:

![image](https://user-images.githubusercontent.com/304786/53552036-5bf2fa00-3b9f-11e9-99e5-a5da4f1c32d4.png)

**Comment by hjoliver** [comment]
Oooh, nice work.  I quite like this version.  And it provides some continuity with the previous logo.

**Comment by matthewrmshin** [comment]
And can't wait to replace the Rose logo with this new design!

**Comment by sadielbartholomew** [comment]
> And can't wait to replace the Rose logo with this new design!

By adding a few more ellipse shapes in appropriate places the this general design concept for Rose could then resemble the petals on a Rose flower, though I am not sure how the coloured circles would then fit... besides possibly depicting actual bugs (as part of an in-joke, of course).

**Comment by sadielbartholomew** [comment]
Not to discredit your great work here @kinow, but I feel inclined to mention that I really like the current (i.e. @hjoliver's original) logo! I would be sad to see it change & actually prefer it over these new suggestions, though I admire your creativity & ideas. Saying that, it could just be a facet of an internal resistance to change.

**Comment by hjoliver** [comment]
Thanks for supporting my old logo @sadielbartholomew!  I'm quite fond of it myself, but it really is too similar to the Google one (above) ... and even if mine did come first, well we probably shouldn't pick a fight with Google :grimacing: ... and in any case, I like @kinow's new one even better.  The black lines really make it stand out more, as well as having (I think) a cool retro sci-fi vibe (nuclear or planet orbitals ...).

**Comment by hjoliver** [comment]
@kinow - as a last step, could you colouring the letters separately as in the original, just in case that looks good.

**Comment by kinow** [comment]
Sure thing @hjoliver ! Will upload the new version in a bit.

**Comment by kinow** [comment]
Attached the latest version with the Tillitium Web font, and the new colours. Screenshot with some guidelines to align elements... I've put the C aligned with the green ball, and the C also "going in" the direction of the other red ball, just to give some sense of alignments between text and other elements :+1: but happy to move things around if necessary. I tried first aligning the text centrally, but the other elements have a bit more of space to the right...

![image](https://user-images.githubusercontent.com/304786/53613547-2c91cb00-3c3b-11e9-9f58-3f4428e92d50.png)


[cylc2.svg.zip](https://github.com/cylc/cylc-admin/files/2917760/cylc2.svg.zip)


And here's the logo exported as PNG:


![cylc03](https://user-images.githubusercontent.com/304786/53613794-12a4b800-3c3c-11e9-8dc9-e1c416ce91ce.png)

Also changed to colours of the lines to a lighter gray. But wonder if they'd look any better in different colours?

Cheers
Bruno

**Comment by hjoliver** [comment]
Hmm, thanks for trying this out, but I think I prefer the black text!  What do you think?

**Comment by hjoliver** [comment]
Maybe lower case "C" at the start too, more balanced?

**Comment by matthewrmshin** [comment]
Vote for black or very dark text. One colour. I prefer the bold version as well.

**Comment by sadielbartholomew** [comment]
Nice work Bruno! 

> Maybe lower case "C" at the start too, more balanced?

> Vote for black or very dark text. One colour.

I agree with both of the above. Though I favor the non-bold text.

**Comment by kinow** [comment]
Maybe one of these? Added some version with dark background, as it's important to see how it would look with reduced palette too :+1: 

![cylc04](https://user-images.githubusercontent.com/304786/53628833-ef483000-3c70-11e9-90a9-649bf3f1067b.png)

My favourites are number 5, which was used for 6/7 (both look OK to me). The text and lines are with a gray colour, but we can have a full black version too if necessary.

**Comment by matthewrmshin** [comment]
Can you also do a gray scale version of 3/5? I like 6 and 7 a lot.

**Comment by kinow** [comment]
Sure, did a 3.1, which is basically the same as 3 or 5 in gray scale. Also added 5, 6, 7 for comparison. They are all the same, only in different colour variations.

![cylc05](https://user-images.githubusercontent.com/304786/53630220-71862380-3c74-11e9-9d96-2976f0d91a26.png)

**Comment by oliver-sanders** [comment]
>  but it really is too similar to the Google one

Google's problem not ours!

**Comment by sadielbartholomew** [comment]
Perhaps we should support *two* official logo variants, one on a light & the other on a dark background. That way, the logo can sit naturally on either a light or dark themed browser page, or app/GUI. It always looks horrible having to merge a logo on a contrasting background into a page (imagine having number 6 as a rectangular black block in the corner of the white Sphinx docs). For our Web UI, it will be simple to incorporate the logo into the dark & light theme(s) we are planning to support.

However, I also think it would be highly preferable to keep the 'dot' colours on both, so that both the dark & light logo would be the same bar being (essentially) inverted other than in those colours, like numbers 5 & 6 from https://github.com/cylc/cylc-admin/issues/5#issuecomment-468608108). It would allow us to keep a distinct & prominent colour set (the red, blue, green & yellow) so we can make it the central, familiar aspect within the themes of our apps (i.e. the Web UI), utilities & documentation, & in other documents, presentations etc.

On that note, my vote is for the pair 5 & 6!

**Comment by hjoliver** [comment]
We should try to resolve this issue before cylc-8.0.0 - the not-very-overwhelming consensus in the Exeter meeting was to stick with the existing logo (because ours came before G**gle's, damn it!). However, I like the new design too.  Just tried a quick experiment (with Gimp) to see what it might look like on the new UI:

Original:

![cylc-color-2](https://user-images.githubusercontent.com/2362137/65649691-bc75e700-e05b-11e9-8eec-89fa9a96d898.png)

New:

![cylc-color-1](https://user-images.githubusercontent.com/2362137/65649698-c26bc800-e05b-11e9-9943-24401f464385.png)

**Comment by kinow** [comment]
The motivation for the new logo was the resemblance with the logo of another company. But if that's not an issue anymore, I'd be fine with either of these two - and once settled, will stop by a store nearby to get a batch of stickers 😄 🎉

**Comment by hjoliver** [comment]
It's not an entirely easy decisions. I still quite like the old one, and being more rectangular it is probably easier to fit into the UI.  But I really like the way the clean orbital lines on the new one add some contrast to the UI (which is otherwise all text and blobs) and anticipates the graph view.

Maybe we can use both, going forward...

**Comment by kinow** [comment]
What I was planning with those orbital lines, was using CSS/animation to move the spheres around... and use that for "Loading..." pages :grimacing:

**Comment by hjoliver** [comment]
I've decided I prefer the new logo for the UI, for the reason I gave just above.  The old one actually looks a bit fat and clunky by comparison.

(Just a final comment for now before getting back to the real work!)

**Comment by hjoliver** [comment]
(Update: we backed out of changing the logo last year due to lack of consensus on the team. I'll close this for now, we can always revisit in the future)
