### ISSUE TITLE
[discussion] Adopt -dev (or similar) suffix to versions

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-admin#51]
Users installing Cylc Flow from the `master` branch, and then running `cylc --version` will have a version like `8.0a0` right now. Some projects adopt a suffix like `-dev` or `-dev1`, dropping the suffix during the release process.

This would make the release process more complicated, but we have https://github.com/cylc/cylc-admin/issues/39 that may help. And this way if a user reports the output of `cylc --version`, we will know immediately whether it was installed via conda/PYPI/tag, or if it was installed from `master`.

Some projects that adopt this are

- Tornado - https://github.com/tornadoweb/tornado/blob/8e5ecad25ea86d52245a9587fd454613f03c7fb8/tornado/
- JupyterHub - https://github.com/jupyterhub/jupyterhub/blob/917786f2f5abdd5163770949c04f507ea0c23d84/jupyterhub/_version.py#L5

We could apply this to Cylc Flow, Cylc UI Server, and even to Cylc UI in the package.json info.

Cheers
Bruno

**Comment by hjoliver** [comment]
I tend to think this is a good idea.  We can implement as soon as (/if) @cylc/core agrees.

**Comment by oliver-sanders** [comment]
I think we used to append the suffix from `git describe` to mark aside the dev version.

**Comment by hjoliver** [comment]
> I think we used to append the suffix from `git describe` to mark aside the dev version.

Yes but we can't do that anymore, for installation by pip from a git clone.

**Comment by kinow** [comment]
I was trying to remember why we removed that, @hjoliver is right. From what I recall, in some cases you may have a copy of the sources with no `.git`, and failing to find the version results in complete failure for pip installation. I think we never tried with Conda, but I suspect similar problem could happen.

**Comment by hjoliver** [comment]
UPDATE: version is now hardwired in `cylc/flow/__init__.py` and updated to append `.dev` between release versions.
