### ISSUE TITLE
Release cylc-xtriggers to Conda Forge

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-admin#83]
@sadielbartholomew fixed some issues in cylc-xtriggers, and then that reminded me that I excluded cylc-xtriggers from the Anaconda `cylc` recipe to save time (was already building too many projects, and just needed to confirm it worked).

Now that we know it works, we can add cylc-xtriggers and have a complete environment, with extra XTriggers loaded via the setuptools plugin system.

There is some commented code that was intended for cylc-xtriggers in `cylc` recipe, but we will need to create a `cylc-xtriggers` recipe from scratch (or from PYPI possibly), upload to a conda channel and update `cylc` recipe.

**Comment by oliver-sanders** [comment]
cylc-xtriggers is dead, we've just bundled the core triggers with Cylc.

If the community has any xtriggers that are generic enough to be of global interest we would be happy to accept them. Other more specialised xtriggers can live in other repositories. We'll look into making xtriggers more plugin-able with https://github.com/cylc/cylc-flow/issues/4106.
