### ISSUE TITLE
Broken links in the cylc-admin homepage

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-admin#91]
Was looking for the instructions to run everything from scratch, to send over to someone in Twitter, and found one broken link: In https://cylc.github.io/cylc-admin/, the very first link is broken: https://cylc.github.io/cylc-admin/howto/environment

Not sure where it's supposed to point.

**Comment by hjoliver** [comment]
That'll be my fault, from recent addition of the Cylc 8 alpha-2 instruction docs.

I'll try to figure out where that link was supposed to point...

Mind you, cylc-admin is not really supposed to be for public consumption.

**Comment by hjoliver** [comment]
Pushed a fix.  The first link is a page @wxtim put up a while ago, I think, it's a bit out of date (e.g. npm instead of yarn).
