### ISSUE TITLE
Automatically upload Conda packages to a personal channel in Conda Forge

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-admin#96]
During the 8.0a2 release, we had several issues that required re-building the packages locally. Besides the inconvenience of having to create environments, and build packages, it looks like `conda install --use-local` may have issues resolving transitive dependencies.

Instead of publishing multiple builds to test, we could have a GitHub action somewhere, manually triggered, that builds and publishes anaconda packages from branches in repositories, to a personal channel.

It would have to build all the packages, choosing the right branch in each repository (it could be a branch of a pending PR)

- conda-forge/cylc-flow
- conda-forge/metomi-isodatetime
- conda-forge/cylc-uiserver
- conda-forge/cylc-ui
- conda-forge/cylc

And run `anaconda upload ...` for each package to upload to a channel (e.g. cylc-test)

This way, we could validate releases with a few commands

- conda create -n cylc-env
- conda activate cylc-env
- conda install cylc --channel cylc-test

**Comment by oliver-sanders** [comment]
This problem hasn't cropped up since. I've had to build cylc-flow (for one of the betas) locally once in order to test what turned out to be a setuptools issue. It seemed to work ok now, we also now have `mamba` as an option if needed.

Closing this issue.
